project_id = "zlmuzknxabuoeilodpad"

[functions.diagnostic-ia]
enabled = true
verify_jwt = true
import_map = "./functions/diagnostic-ia/deno.json"
entrypoint = "./functions/diagnostic-ia/index.ts"

[functions.filter-message]
enabled = true
verify_jwt = true
import_map = "./functions/filter-message/deno.json"
entrypoint = "./functions/filter-message/index.ts"

[functions.notif-whatsapp]
enabled = true
verify_jwt = true
import_map = "./functions/notif-whatsapp/deno.json"
entrypoint = "./functions/notif-whatsapp/index.ts"

[functions.lovable-chat]
enabled = true
verify_jwt = true
import_map = "./functions/lovable-chat/deno.json"
entrypoint = "./functions/lovable-chat/index.ts"

[functions.initiate-payment]
enabled = true
verify_jwt = true
import_map = "./functions/initiate-payment/deno.json"
entrypoint = "./functions/initiate-payment/index.ts"

[functions.send-push]
enabled = true
verify_jwt = true
import_map = "./functions/send-push/deno.json"
entrypoint = "./functions/send-push/index.ts"
